### ISSUE TITLE
enumerate on scrape all

### ISSUE THREAD

**Issue by LukasHolzner** [julhac/datagorri#30]
When using scrape all (#6) to select all elements/columns the user has to fill in every output label. There should be a standard enumeration, so the user does not have to fill in all the labels.

**Comment by LukasHolzner** [comment]
@julhac Should the labels be removed if the scrape all checkbutton is deselected?

**Comment by julhac** [comment]
I suggest the labels should remain. If you did the effort of entering labels, you might at least want to keep those, even if you are going to scrape a subset. If you also want to delete the labels you can still restart datagorri. What happens if I click the scrape all button, deselect it and re-click it? Are previously entered labels overwritten with numbers? Maybe this should not happen. That is, only empty elements are numbered.

**Comment by LukasHolzner** [comment]
@julhac all requested changes were made. If you have something to add plaese reopen this issue or create a new one.
